FROM node:18-alpine

RUN npm install -g pnpm

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./package.json ./pnpm-lock.yaml ./

ENV PATH /usr/src/app/node_modules/.bin:$PATH

WORKDIR /usr/src/app

COPY ./ .

RUN pnpm install --frozen-lockfile

## How variabilize the snapshot name
RUN npx directus schema apply --yes ./2022-12-29-snapshot-1672344346.yaml

CMD ["pnpm", "start"]