FROM node:18-alpine

RUN npm install -g pnpm

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./package.json ./pnpm-lock.yaml ./

ENV PATH /usr/src/app/node_modules/.bin:$PATH

WORKDIR /usr/src/app

COPY ./ .

RUN pnpm install --frozen-lockfile

# CMD ["pnpm", "start"]